export const BUY_MOB='BUY_MOB';
export const BUY_TAB='BUY_TAB';
export const FETCH_USERS_REQUEST='FETCH_USERS_REQUEST';
export const FETCH_DATA_SUCCESS='FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAILURE='FETCH_DATA_FAILURE';

